language: python
branches:
        only: master
env:
        - TOX_ENV="py27"
        - TOX_ENV="py33"
        - TOX_ENV="py34"
        - TOX_ENV="flake8"

install: 
        - travis_retry sudo apt-get update
        - travis_retry pip install tox
        - "pip install flake8 --use-mirrors"
        - "pip install -r requirements.txt --use-mirrors"
        - "[ ! -z $COVERAGE ] && travis_retry pip install coveralls || true"

script: tox -e $TOX_ENV
before_script: "flake8 --ignore=F821"
after_success:
        - "[ ! -z $COVERAGE ] && coveralls || true"
