language: python
matrix:
    include:
        - os: linux
          python: 3.9
          env: TOX_ENV=coverage
          sudo: required
          dist: focal
        - os: linux
          python: 3.9
          env: TOX_ENV=flake8
          sudo: required
          dist: focal
        - os: linux
          python: 3.7
          env: TOX_ENV=py37
          sudo: required
          dist: focal
        - os: linux
          python: 3.8
          env: TOX_ENV=py38
          sudo: required
          dist: focal
        - os: linux
          language: python
          python: 3.9
          env: TOX_ENV=py39
          sudo: required
          dist: focal

install:
    - travis_retry sudo apt-get update
    - travis_retry pip install tox
    - travis_retry pip install poetry

script: tox -e $TOX_ENV
